name: Release

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-18.04
    name: build target
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: ProtoByter/run-on-arch-action@v2.1.4
        name: Run commands
        id: runcmd
        with:
          arch: riscv64
          distro: alpine_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          # uname -az
          run: |
            apk add make 
            apk add gcc musl-dev g++ zlib-dev
            apk add autoconf
            gcc
            ln -s /usr/include/linux /usr/include/riscv64-linux-musl/linux
            ln -s /usr/include/asm-generic /usr/include/riscv64-linux-musl/asm
            ln -s /usr/include/mtd /usr/include/riscv64-linux-musl/mtd
            cp /usr/include/riscv64-linux-gnu/asm/byteorder.h /usr/include/asm-generic
            make

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"